### ISSUE TITLE
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]'

### ISSUE THREAD

**Issue by SunZeDong** [fplll/g6k#5]
When testing the samples of g6k, all report this error:

Traceback (most recent call last):
  File "./full_sieve.py", line 76, in <module>
    full_sieve()
  File "./full_sieve.py", line 50, in full_sieve
    args, all_params = parse_args(description,)
  File "/home/shamir/Desktop/packages/g6k-master/g6k/utils/cli.py", line 253, in parse_args
    log_filename = log_filenamef()
  File "/home/shamir/Desktop/packages/g6k-master/g6k/utils/cli.py", line 142, in log_filenamef
    revision = git_revisionf()
  File "/home/shamir/Desktop/packages/g6k-master/g6k/utils/cli.py", line 131, in git_revisionf
    r = str(subprocess.check_output(cmd).rstrip())
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('git', 'show', '-s', '--format=%cd', 'HEAD', '--date=short')' returned non-zero exit status 128

I searched the Internet and talked with my classmates but couldn't figure out it.
Thanks.

**Comment by SunZeDong** [comment]
At first, error is as below:
**fatal: not a git repository (or any of the parent directories): .git**
Traceback (most recent call last):
  File "./svp_exact_find_norm.py", line 90, in <module>
    svp()
  File "./svp_exact_find_norm.py", line 78, in svp
    challenge_seed=0)
  File "/home/mrshamir/Desktop/packages/g6k-master/g6k/utils/cli.py", line 253, in parse_args
    log_filename = log_filenamef()
  File "/home/mrshamir/Desktop/packages/g6k-master/g6k/utils/cli.py", line 142, in log_filenamef
    revision = git_revisionf()
  File "/home/mrshamir/Desktop/packages/g6k-master/g6k/utils/cli.py", line 131, in git_revisionf
    r = str(subprocess.check_output(cmd).rstrip())
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('git', 'show', '-s', '--format=%cd', 'HEAD', '--date=short')' returned non-zero exit status 128
Then I use "git init" and it became error above.
But the origin is the **### subprocess.CalledProcessError: Command '('git', 'show', '-s', '--format=%cd', 'HEAD', '--date=short')' returned non-zero exit status 128**

**Comment by malb** [comment]
Looks like our script gets confused with your git set up, you can probably just comment out the offending line and write `revision = "foo"`
