### ISSUE TITLE
ValueError: Parameters 71, 51, 81 do not satisfy constraint  0 <= ll <= l <= r <= self.M.d

### ISSUE THREAD

**Issue by Summwer** [fplll/g6k#78]
Hello, Developer.
 When I was calling the g6k to solve the lwe problem in \alpha = 0.001953125 . It occurs the error like the following:
```
Primal attack, LWE challenge n=40, alpha=0.0020
Chose 80 samples. Predict solution at bkz-40 + svp-40

GSO precision:  double
Intial Slope = -0.07619

Starting a fpylll BKZ-10 tour.  slope: -0.07480, walltime: 0.111 sec
Without otf, would expect solution at pump-2. n_max=48 in the given time.
Starting svp pump_{71, 10, -39}, n_max = 49, Tmax= 0.11 sec
Traceback (most recent call last):
  File "lwe_challenge.py", line 289, in <module>
    lwe()
  File "lwe_challenge.py", line 279, in lwe
    stats = run_all(lwe_kernel, list(all_params.values()), # noqa
  File "/home/summer/g6k/g6k/utils/cli.py", line 114, in run_all
    res = f(copy.deepcopy(job))
  File "lwe_challenge.py", line 229, in lwe_kernel
    pump(g6k, tracer, llb, d-llb, f, verbose=verbose,
  File "/home/summer/g6k/g6k/algorithms/pump.py", line 106, in pump
    g6k.initialize_local(kappa, max(pump.r-start_up_n, pump.l+1), pump.r)
  File "g6k/siever.pyx", line 286, in g6k.siever.Siever.initialize_local
    raise ValueError("Parameters %d, %d, %d do not satisfy constraint  0 <= ll <= l <= r <= self.M.d"%(ll, l, r))
ValueError: Parameters 71, 51, 81 do not satisfy constraint  0 <= ll <= l <= r <= self.M.d

```

And my input file is :

```
40
80
256
0.001953125
[77 158 225 129 73 114 230 93 194 237 130 235 161 13 98 216 154 248 72 235 67 82 178 254 206 74 15 104 253 15 101 18 152 19 158 60 51 185 147 110 147 116 46 217 246 78 116 185 22 152 226 147 27 16 92 210 97 193 47 34 175 87 58 77 112 104 5 155 249 170 3 25 124 140 246 155 77 124 126 220 ]
[[214 77 146 93 255 159 161 128 23 73 29 213 29 171 206 228 194 102 199 74 64 180 58 35 73 205 230 234 221 187 72 232 156 124 242 187 184 70 107 32]
[251 80 97 32 110 24 86 246 4 170 237 182 71 240 185 251 175 189 137 59 208 86 221 128 252 146 147 69 128 80 8 223 24 142 160 5 181 118 180 94]
[99 29 106 76 133 36 137 243 68 48 252 20 181 234 242 121 215 37 169 56 200 189 16 250 64 115 136 40 45 185 127 103 74 249 137 69 107 137 158 113]
[252 209 79 191 233 211 87 56 161 69 210 74 198 103 87 117 147 37 178 158 110 130 6 74 125 122 57 33 198 66 12 122 204 4 247 216 187 173 247 126]
[169 68 251 60 128 44 3 32 204 248 228 0 205 170 10 49 95 87 244 53 151 231 251 45 74 255 188 238 56 145 88 93 89 106 248 84 97 66 15 63]
[68 234 145 143 47 50 69 13 63 163 181 113 120 206 176 175 124 204 108 76 153 251 72 109 193 249 54 62 132 231 233 246 95 218 0 254 38 58 181 36]
[179 101 5 60 100 98 198 151 62 24 163 25 210 15 113 55 208 121 219 12 57 238 18 250 83 206 213 165 233 163 140 223 132 92 59 142 195 98 211 137]
[213 83 93 3 199 55 156 53 97 11 193 121 149 23 211 229 26 44 211 200 148 101 255 195 68 72 230 119 143 134 248 229 174 37 120 142 85 212 65 84]
[41 9 65 66 223 191 34 56 161 176 253 65 59 76 6 100 153 50 141 146 212 126 174 5 191 31 193 91 109 160 102 8 131 4 68 235 220 174 137 152]
[28 103 234 31 76 158 236 15 77 64 102 168 167 121 145 158 192 37 150 152 25 87 11 88 27 250 58 10 103 86 164 253 35 201 205 196 4 226 98 172]
[129 125 94 125 66 216 202 81 64 238 44 61 122 180 200 243 38 81 40 250 169 100 12 154 133 158 216 30 108 137 48 227 157 194 250 108 171 83 210 203]
[80 32 92 20 247 87 58 85 226 224 154 93 171 145 56 4 180 31 160 76 172 247 159 153 152 153 56 105 243 103 230 138 237 78 46 38 22 171 136 90]
[138 107 164 246 160 144 95 80 8 120 153 198 140 198 156 105 57 67 32 189 2 152 136 115 59 116 164 191 240 165 96 209 133 31 215 27 53 214 11 121]
[97 53 10 241 144 238 47 254 58 75 192 205 125 100 0 188 106 33 24 132 220 238 54 20 114 27 91 135 77 44 171 24 19 51 249 224 225 32 134 197]
[2 225 131 249 248 10 93 2 176 251 140 72 41 78 251 20 94 240 10 78 250 58 10 101 46 127 30 107 8 5 165 123 58 153 72 87 127 58 31 44]
[71 175 240 250 127 110 245 85 184 237 129 58 238 66 13 174 118 194 194 237 231 59 217 243 31 134 39 167 69 237 201 74 68 95 99 141 183 192 63 75]
[209 160 64 172 121 235 87 47 146 251 57 102 222 254 5 149 95 66 203 80 75 41 211 155 89 225 49 237 214 34 160 45 253 33 48 234 134 42 161 203]
[132 27 65 132 18 14 146 169 132 154 88 178 8 205 43 101 23 182 14 175 17 17 85 50 39 189 171 117 224 92 200 4 251 218 249 47 119 17 98 24]
[3 90 27 178 116 37 217 213 181 88 122 39 162 141 176 127 36 211 94 212 59 82 43 2 195 26 230 171 167 73 93 126 20 99 208 200 190 223 41 6]
[86 20 2 32 99 13 221 12 220 30 13 188 209 9 100 215 127 121 122 190 223 159 48 88 187 245 24 65 169 202 149 159 251 10 241 161 123 113 16 144]
[227 69 94 51 170 32 25 98 201 201 15 120 4 110 243 60 218 142 145 182 89 209 230 38 129 78 30 144 24 154 70 17 47 57 144 33 214 108 164 36]
[122 72 155 135 188 187 85 28 198 85 144 176 242 41 145 108 105 221 74 93 89 185 252 84 104 108 211 110 179 3 234 202 204 40 127 175 129 75 205 55]
[29 62 244 248 181 234 227 109 37 238 71 204 82 204 55 93 172 234 129 194 248 22 192 200 137 130 212 55 194 33 253 79 115 133 96 254 201 36 33 179]
[74 4 179 168 104 163 74 213 121 161 255 250 94 188 158 114 195 245 254 21 63 194 111 87 216 179 41 16 190 183 55 64 37 82 39 85 149 95 167 159]
[113 178 200 69 34 157 119 74 145 36 94 172 145 245 78 182 42 125 161 44 31 126 183 147 163 13 159 211 99 242 213 142 134 73 38 163 98 86 101 78]
[219 126 232 58 97 32 13 255 105 5 28 136 105 160 52 218 184 75 120 91 167 146 89 230 40 150 212 62 82 139 2 245 75 247 18 158 29 156 74 223]
[158 195 166 110 255 46 83 164 174 122 44 103 217 115 15 74 237 122 38 232 151 8 112 250 89 26 124 40 26 36 165 97 64 151 113 74 255 57 125 247]
[45 58 239 30 133 253 192 114 124 79 2 108 182 185 7 250 179 134 83 38 77 163 52 207 79 104 11 136 188 170 107 134 39 56 167 191 225 56 96 47]
[92 6 182 76 146 33 131 46 177 228 222 112 90 45 47 116 234 106 134 54 213 194 51 209 217 82 179 32 241 200 35 112 237 63 147 158 104 15 32 107]
[82 70 166 106 131 252 80 197 175 216 45 62 51 224 228 235 83 160 116 159 107 163 212 130 149 107 175 143 59 13 191 154 18 248 136 38 207 236 41 57]
[193 124 118 249 207 93 63 26 20 24 169 126 134 105 221 72 59 154 239 25 221 58 31 117 65 200 159 78 111 103 152 80 106 246 3 234 88 144 17 211]
[172 240 168 114 208 45 5 194 106 187 145 149 205 211 106 166 41 87 247 191 88 235 252 93 126 115 200 157 66 125 195 98 240 68 220 79 33 74 157 74]
[143 243 12 204 42 72 162 74 22 231 104 127 227 78 251 152 123 148 170 137 43 105 71 149 123 213 66 211 4 48 239 152 234 157 234 47 74 47 155 137]
[178 30 99 62 141 50 145 200 169 195 153 0 121 191 108 36 7 32 135 143 255 99 144 82 134 70 170 150 147 144 247 150 233 36 212 238 85 204 134 187]
[192 32 151 117 51 112 6 211 244 0 200 233 87 253 169 6 50 6 191 204 98 72 42 129 123 129 153 167 130 159 206 21 24 51 222 245 68 161 60 31]
[13 100 14 13 72 117 211 239 155 134 85 181 146 210 138 186 56 27 215 98 251 255 103 246 248 53 165 44 215 36 70 97 56 114 175 174 215 189 226 13]
[162 196 127 30 6 250 156 250 117 111 83 213 9 16 129 24 132 42 1 131 191 2 75 67 184 87 98 213 129 205 188 113 37 105 219 9 244 97 42 166]
[52 110 117 1 240 194 87 101 152 247 146 157 143 190 65 187 86 250 25 85 38 69 239 69 189 183 6 23 93 141 207 46 131 237 22 112 254 246 9 14]
[0 140 237 138 155 27 53 134 9 252 149 225 111 185 109 54 101 0 32 244 253 240 242 7 156 190 16 51 217 238 152 8 206 36 63 148 4 207 46 5]
[88 116 44 178 131 189 116 121 41 243 124 178 182 172 70 196 77 251 192 245 129 182 50 24 132 242 191 247 150 112 126 35 90 151 110 199 194 220 210 152]
[178 42 250 255 224 164 137 237 59 104 49 139 95 206 88 104 165 94 31 60 217 32 237 23 190 115 41 223 219 102 133 213 231 137 229 215 167 63 106 1]
[131 142 218 130 37 239 13 144 154 167 254 119 129 33 173 226 65 152 198 158 7 154 92 63 190 187 180 85 214 76 230 88 118 39 152 73 85 185 86 247]
[166 29 90 103 12 34 221 78 188 107 187 36 201 150 5 89 125 130 234 27 4 25 175 148 21 227 200 104 57 39 194 28 191 102 4 97 210 131 233 160]
[133 134 191 215 78 60 133 78 241 72 13 65 54 139 198 35 223 99 36 110 24 135 233 45 136 121 50 152 228 55 32 231 150 7 232 172 108 95 204 140]
[163 113 234 239 170 125 33 222 143 9 161 141 16 130 8 225 140 57 120 28 100 108 48 242 201 246 192 93 50 228 66 28 21 33 235 18 93 198 74 37]
[120 107 218 15 14 222 104 100 112 227 238 15 181 55 138 95 182 46 195 177 246 117 0 122 89 188 211 251 198 7 209 147 208 58 220 112 69 238 45 48]
[54 99 23 21 78 186 128 167 131 79 34 100 255 183 171 165 151 93 86 78 37 50 16 216 209 29 168 68 129 240 97 226 177 56 130 98 5 99 58 37]
[121 97 210 204 81 89 77 66 23 176 36 188 140 218 139 160 47 254 90 165 156 130 220 154 121 117 146 16 20 27 17 30 78 63 69 135 74 253 57 248]
[252 11 24 61 208 253 189 1 162 233 160 84 244 24 250 96 57 142 35 120 58 207 60 141 63 67 59 2 188 25 116 152 246 132 138 83 125 212 104 71]
[10 125 165 222 113 216 177 190 67 51 127 172 34 202 103 28 229 135 179 21 71 223 203 113 193 146 6 121 160 158 49 117 11 141 96 153 114 128 22 50]
[224 252 16 53 166 62 84 122 63 209 168 201 111 203 137 102 27 131 23 237 30 194 185 173 10 23 146 237 228 207 21 250 93 104 183 46 73 87 158 63]
[140 178 144 177 50 25 245 241 199 219 255 239 149 94 254 197 254 170 108 101 255 242 239 113 102 197 99 94 74 152 11 64 177 172 151 124 241 132 15 186]
[183 169 160 184 50 215 90 175 55 104 111 184 185 5 146 170 212 183 226 156 17 80 110 243 245 19 36 209 160 134 68 151 144 148 92 186 43 60 61 229]
[99 243 34 102 176 246 88 232 104 144 98 24 102 213 97 243 105 51 168 197 79 17 28 51 55 193 8 222 169 65 155 255 55 246 112 203 170 6 141 26]
[144 71 164 214 211 111 123 71 9 46 76 151 181 235 253 132 176 9 52 204 181 217 0 80 84 19 107 26 101 5 20 94 100 12 197 246 241 125 226 149]
[224 100 53 250 117 249 86 13 219 225 161 226 194 88 5 186 5 216 52 210 3 39 227 33 121 42 9 173 105 161 20 177 8 180 143 105 103 52 217 141]
[77 117 21 31 156 93 48 102 175 35 104 106 158 153 195 196 99 205 149 26 105 105 119 116 235 126 109 63 198 94 35 1 161 222 17 43 15 255 25 151]
[101 56 117 237 233 214 206 185 50 116 152 6 61 234 38 132 163 106 59 17 20 221 62 221 120 108 229 157 220 100 161 20 91 190 82 212 132 114 131 27]
[230 71 91 94 180 172 32 66 66 148 224 105 141 182 128 167 61 87 200 68 111 13 49 190 190 184 167 132 233 42 39 126 201 189 161 26 62 54 194 166]
[28 160 150 147 144 171 75 21 194 130 173 139 117 247 44 246 56 156 54 71 55 163 217 218 81 64 227 221 119 210 231 228 227 124 149 209 162 211 77 149]
[218 4 196 3 87 156 204 62 190 85 61 1 20 233 212 122 12 213 251 114 90 122 242 166 139 204 199 120 96 239 87 41 67 164 165 184 207 53 9 23]
[41 59 174 227 39 101 89 216 152 148 125 101 92 32 158 103 8 143 136 95 129 84 244 134 37 67 58 49 62 176 206 46 94 175 88 118 66 198 0 78]
[125 152 127 104 53 103 212 201 185 8 224 194 72 150 158 138 152 8 153 255 95 86 239 50 106 108 71 75 171 179 135 142 213 147 70 140 247 111 37 83]
[247 183 232 114 151 86 157 229 34 65 23 248 161 131 244 163 49 156 209 137 50 249 208 67 248 234 5 225 18 233 165 151 197 72 215 106 121 157 147 255]
[236 178 138 77 236 183 168 226 239 183 42 133 213 182 246 209 197 23 26 73 145 52 224 64 64 239 109 154 130 219 237 115 66 59 171 145 137 2 89 84]
[84 192 127 97 42 99 157 90 85 160 66 63 211 77 16 182 198 170 4 159 152 152 247 244 67 80 159 103 74 89 177 149 230 238 148 71 127 133 17 226]
[234 168 207 177 142 38 199 10 98 27 66 29 189 51 70 38 220 203 240 182 8 240 81 247 125 4 223 34 250 29 43 99 249 17 224 48 227 25 185 169]
[233 97 16 255 197 125 239 135 238 115 212 204 201 217 236 27 34 167 207 234 69 122 5 231 45 79 239 0 182 250 132 181 57 23 222 89 112 112 193 66]
[129 194 29 33 176 232 173 93 134 33 78 163 92 118 94 221 65 176 178 95 179 192 154 174 3 247 241 171 84 58 162 131 83 43 110 115 125 254 205 35]
[162 49 155 131 106 63 57 154 79 92 163 5 90 4 232 122 81 116 130 74 20 217 32 207 116 192 194 122 179 189 253 0 79 195 19 21 171 51 26 143]
[38 33 117 151 170 182 84 153 86 238 145 89 205 58 76 61 182 82 250 183 90 198 194 76 207 82 81 19 84 214 86 106 14 76 108 159 160 213 167 202]
[51 187 38 39 126 80 177 249 238 86 35 127 89 164 54 145 174 7 238 95 97 9 86 220 48 198 40 99 108 145 25 123 232 215 244 157 102 52 28 241]
[229 162 21 248 124 26 79 163 10 236 237 101 236 66 84 255 78 252 202 168 133 189 197 243 234 189 126 222 190 18 220 63 140 39 8 151 118 45 93 161]
[77 219 126 232 145 1 40 135 193 17 29 20 148 211 100 23 50 132 79 139 161 230 31 182 172 248 139 25 179 25 213 188 95 84 233 141 207 49 153 108]
[242 16 133 31 137 3 52 200 238 52 137 135 2 142 203 24 48 168 8 19 223 149 68 30 149 146 211 246 216 140 77 200 188 12 148 241 221 252 98 64]
[160 89 171 175 72 36 58 18 251 238 8 138 218 201 207 216 10 42 228 120 107 172 107 19 221 127 201 137 89 68 158 199 28 120 96 4 20 145 135 17]
[55 55 136 125 158 32 30 115 87 136 153 126 168 92 122 38 156 249 99 156 123 22 14 9 50 48 43 198 155 204 190 213 38 234 191 47 116 177 182 67]
[121 188 208 45 162 154 163 251 117 73 99 217 149 6 230 252 226 84 217 48 15 254 74 165 42 110 51 112 170 26 71 238 90 45 221 178 37 12 59 5]
[212 138 42 245 113 189 80 59 51 69 228 55 154 131 218 194 20 142 245 241 23 8 17 134 63 83 241 202 241 107 41 157 234 32 218 127 46 139 17 87]
[70 71 134 102 203 168 21 169 48 47 214 93 53 77 120 190 230 232 146 17 184 29 219 212 51 8 250 61 78 242 223 88 12 99 243 120 239 211 252 177]
]
```

**Comment by verdiverdiverdi** [comment]
Dear Summwer,

Thank you for this issue. I have a pull request ready which fixes the indexing issues – but I was wondering how you generated this LWE instance? I cannot solve it even using reduction that should be more than sufficient for this error rate.

For reference, after saving the file you attach as g6k/lwechallenge/040-002-solution.txt I'm running

`python lwe_challenge.py 40 --lwe/alpha 0.002 --lwe/m 80`

to reproduce your instance.

**Comment by Summwer** [comment]
Sorry, I don't know how to generate this lwe instance,either. It's a problem proposed by holders of a cryptography competition in China.

**Comment by Summwer** [comment]
> Dear Summwer,
> 
> Thank you for this issue. I have a pull request ready which fixes the indexing issues – but I was wondering how you generated this LWE instance? I cannot solve it even using reduction that should be more than sufficient for this error rate.
> 
> For reference, after saving the file you attach as g6k/lwechallenge/040-002-solution.txt I'm running
> 
> `python lwe_challenge.py 40 --lwe/alpha 0.002 --lwe/m 80`
> 
> to reproduce your instance.

I've looked back the explaination of generation of the lwe instance by holders, they told me that since the dimension is small, so e is not strictly fit for the Gaussian distribution, but it's norm is small obsolutely. Thus, there possibly no solution when alpha is smaller than 0.02. Thanks for debugging anymore. My best wishes~
