### ISSUE TITLE
Some problem about Sieve

### ISSUE THREAD

**Issue by mad-jcbx** [fplll/g6k#98]
I want to arise the dimension of IntegerMatrix of random in Sieve , but got a ValueError: Float type 'dd' unknown.

My code is :
A = IntegerMatrix.random(320, "qary", k=160,q=256)
print (A)
g6k = Siever(A)

The error :
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    g6k = Siever(A)
  File "g6k/siever.pyx", line 85, in g6k.siever.Siever.__init__
    M = self.MatGSO(M, float_type=float_type)
  File "g6k/siever.pyx", line 127, in g6k.siever.Siever.MatGSO
    M = GSO.Mat(A, float_type=float_type,
  File "src/fpylll/fplll/gso.pyx", line 175, in fpylll.fplll.gso.MatGSO.__init__
  File "src/fpylll/util.pyx", line 54, in fpylll.util.check_float_type
ValueError: Float type 'dd' unknown.

I don't know how to fix it.T T

**Comment by joerowell** [comment]
We recently addressed this problem (#96 ). The wiki link in that answer ( https://github.com/fplll/fpylll/wiki/Float-Type-unknown ) tells you how to fix this.
